- name: PLAY-1
  hosts: web
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
     msg: "I am from Play-1 and Task-1"

- name: PLAY-2
  hosts: web
  tasks:  
  - name: PLAY-2 and TASK-1
    ansible.builtin.debug:
     msg: "I am from Play-2 and Task-1"


#Output:

# [ ec2-user@ip-172-31-28-238 ~/ansible ]$ ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 03-multi-play.yaml

# PLAY [PLAY-1] ************************************************************************************************************************

# TASK [Gathering Facts] ***************************************************************************************************************
# ok: [172.31.21.180]

# TASK [PLAY-1 and TASK-1] *************************************************************************************************************
# ok: [172.31.21.180] => {
#     "msg": "I am from Play-1 and Task-1"
# }

# PLAY [PLAY-2] ************************************************************************************************************************

# TASK [Gathering Facts] ***************************************************************************************************************
# ok: [172.31.21.180]

# TASK [PLAY-2 and TASK-1] *************************************************************************************************************
# ok: [172.31.21.180] => {
#     "msg": "I am from Play-2 and Task-1"
# }

