- name: variables
  hosts: web
  vars:
    Trainer: "Siva"
    Duration: "120 weeks"
    Course: "Devops and AWS"
  tasks:
  - name: Print Information
    ansible.builtin.debug:
      msg: "Hi we are doing a Course on {{Course}}, Trainer is: {{Trainer}}, Duration is: {{Duration}}"