- name: Usage of Vars file at PLAY level
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: Inside TASK level
    vars:
      DURATION: "120 hours"
    ansible.builtin.module:
      msg: "Course: {{Course}}, Trainer: {{Trainer}}"