- name: Usage of Vars file at PLAY level
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: Inside TASK level
    vars:
      Duration: "120 hours"
    ansible.builtin.debug:
     msg: "Course: {{Course}}, Trainer: {{Trainer}}, Duration: {{Duration}}"


#Output:

# [ ec2-user@ip-172-31-28-238 ~/ansible ]$ ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 06-vars-files.yaml

# PLAY [Usage of Vars file at PLAY level] **********************************************************************************************

# TASK [Gathering Facts] ***************************************************************************************************************
# ok: [172.31.21.180]

# TASK [Inside TASK level] *************************************************************************************************************
# ok: [172.31.21.180] => {
#     "msg": "Course: Devops, Trainer: Siva, Duration: 3months"
    