- name: Usage of vars_prompt
  hosts: web

  vars_prompt:
  - name: USERNAME
    prompt: Pls enter your Username:
    private: false
  - name: PASSWORD
    promt: Pls enter your Password:
    private: true
  
  tasks:
  - name: Task level printing information
    ansible.builtin.debug:
      msg: "Username is: {{USERNAME}} and Password is: {{PASSWORD}}"
  