- name: Testing variables inside inventory.ini file
  hosts: localhost2
  tasks:
  - name: Print info at task level
    vars:
      Timings: "7.15AM"
    ansible.builtin.debug:
      msg: "Course is: {{Course}}, Trainer is: {{Trainer}}, Duration is: {{Duration}}, Timings are: {{Timings}}"