- name: Testing variable preference at Play/Task/Arg/Var/Varfile/Inventory/Prompt levels
  hosts: localhost
  #vars:
  #  WISHES: Morning from PLAY variable.
  #vars_files:
  #- vars.yaml
  #vars_prompt:
  #- name: WISHES
  #  prompt: Pls enter your Wishes
  #  private: false
  tasks:
  - name: Test inside Task level
  # vars:
  #   WISHES: Morning from TASK variable
    ansible.builtin.debug:
      msg: "{{WISHES}}"

  #Preference:
  # 1. Testing-from-Arg-level
  # 2. Morning from TASK variable
  # 3. Morning from VARS FILE
  # 4. Morning from PROMPT
  # 5. Morning from PLAY variable.
  # 6. 