- name: Command Module Usage
  hosts: localhost
  tasks:
  - name: Check if user expense exists
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true
  - name: Print the USER information
    ansible.builtin.debug:
      msg: "USER Information: {{USER}}"
  - name: Create User Expense if that does not exist
    ansible.builtin.command: useradd expense
    when: USER.rc != 0 #condition
  - name: Printing last message
    ansible.builtin.debug:
      msg: "Hello this is end of message."