- name: print default value
  hosts: localhost
  tasks:
  - name: printing default value
    ansible.builtin.debug:
      msg:  "Hello, Good {{MESSAGE  | default('Morning')  }}"

- name: upper case
  hosts: localhost
  tasks:
  - name: converting string to upper case
    vars:
      greeting: "How are you doing buddy?"
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: lower case
  hosts: localhost
  vars:
    - greeting: "I AM DOING GREAT..."
  tasks:
    - name: converting to lower case
      ansible.builtin.debug:
        msg:  "{{greeting | lower}}"