- name: print default value
  hosts: localhost
  tasks:
  - name: printing default value
    ansible.builtin.debug:
      msg:  "Hello, Good {{MESSAGE  | default('Morning')  }}"

- name: upper case
  hosts: localhost
  tasks:
  - name: converting string to upper case
    vars:
      greeting: "How are you doing buddy?"
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: lower case
  hosts: localhost
  vars:
    - greeting: "I AM DOING GREAT..."
  tasks:
    - name: converting to lower case
      ansible.builtin.debug:
        msg:  "{{greeting | lower}}"

- name: minimum and maximum values
  hosts: localhost
  vars:
    ages: [25, 20, 34, 78, 45]
  tasks: 
  - name: printing min and max age
    ansible.builtin.debug:
      msg:  "Min Age is {{ages  | min}}, Max Age is {{ages  | max}}" 

- name: remove duplicates
  hosts: localhost
  vars:
    - duplicates [1,1,4,4,6,7,8,8]      
  tasks:
  - name: duplicate removal using unique keyword
    ansible.builtin.msg:
      msg:  {{duplicates |  unique}}    
